name: Build, Test, and Push Sherehe Backend (Prod or Dev)

on:
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: shereheuser
          POSTGRES_PASSWORD: secretpassword
          POSTGRES_DB: sherehe
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U shereheuser -d sherehe"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5

    env:
      NODE_ENV: test
      PORT: 3000
      DB_USER: shereheuser
      DB_PASSWORD: secretpassword
      DB_NAME: sherehe
      DB_HOST: localhost
      DB_PORT: 5432
      PGUSER: shereheuser
      PGPASSWORD: secretpassword
      PGDATABASE: sherehe
      PGHOST: localhost
      PGPORT: 5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run migrations
        run: npx node-pg-migrate up

      - name: Run tests
        run: npm test

  build-and-push:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install pack CLI
        run: |
          curl -sSL "https://github.com/buildpacks/pack/releases/download/v0.38.2/pack-v0.38.2-linux.tgz" | tar -xz
          sudo mv pack /usr/local/bin/pack

      - name: Cache CNB Layers
        uses: actions/cache@v4
        with:
          path: ~/.cache/pack
          key: cnb-${{ runner.os }}-${{ github.ref }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            cnb-${{ runner.os }}-${{ github.ref }}
            cnb-${{ runner.os }}

      - name: Set Docker tags
        id: tags
        run: |
          BRANCH=$(echo "${GITHUB_REF##*/}" | tr '[:upper:]' '[:lower:]' | tr '/' '-')
          SHA=$(git rev-parse --short HEAD)
          
          if [ "$BRANCH" = "main" ]; then
            IMAGE_TAG="prod"
            IMAGE_BASE="${{ secrets.DOCKERHUB_USERNAME }}/sherehe-backend-prod"
          else
            IMAGE_TAG="dev"
            IMAGE_BASE="${{ secrets.DOCKERHUB_USERNAME }}/sherehe-backend-staging"
          fi
          
          echo "image_base=$IMAGE_BASE" >> $GITHUB_OUTPUT
          echo "image_tag=$IMAGE_TAG" >> $GITHUB_OUTPUT
          echo "sha_tag=$SHA" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker image with Buildpacks
        run: |
          IMAGE_BASE=${{ steps.tags.outputs.image_base }}
          IMAGE_TAG=${{ steps.tags.outputs.image_tag }}
          SHA_TAG=${{ steps.tags.outputs.sha_tag }}
          
          # Build the image without --publish first
          # This ensures the image exists locally for the explicit docker push step
          echo "🔨 Building $IMAGE_BASE:$IMAGE_TAG and $IMAGE_BASE:$SHA_TAG"
          pack build "$IMAGE_BASE:$IMAGE_TAG" \
            --buildpack paketo-buildpacks/nodejs \
            --builder paketobuildpacks/builder-jammy-base \
            --env NODE_ENV=production \
            --cache "type=build;format=volume"
          
          # Tag the SHA version explicitly for consistent pushing
          docker tag "$IMAGE_BASE:$IMAGE_TAG" "$IMAGE_BASE:$SHA_TAG"

      - name: Push Docker images to Docker Hub
        run: |
          IMAGE_BASE=${{ steps.tags.outputs.image_base }}
          IMAGE_TAG=${{ steps.tags.outputs.image_tag }}
          SHA_TAG=${{ steps.tags.outputs.sha_tag }}
          
          echo "🚀 Pushing $IMAGE_BASE:$IMAGE_TAG"
          docker push "$IMAGE_BASE:$IMAGE_TAG"
          
          echo "🚀 Pushing $IMAGE_BASE:$SHA_TAG"
          docker push "$IMAGE_BASE:$SHA_TAG"
